donghunseol/social-lize

- src/main/resources/templates/layout/profilemodal.mustache
> 모달 프로필사진 수정

- src/main/java/com/example/project/board/BoardController.java
- src/main/resources/static/css/style.css
- src/main/resources/templates/board/board.mustache
- src/main/resources/templates/layout/footer.mustache
> 내부-메인-게시글 화면

- src/main/resources/static/css/socialadd.css
- src/main/resources/static/css/style.css
- src/main/resources/templates/layout/footer.mustache
- src/main/resources/templates/layout/header.mustache
- src/main/resources/templates/social/socialaddForm.mustache
> 소셜애드 페이지, 헤더수정, 푸터수정

- src/main/java/com/example/project/social/Social.java
- src/main/java/com/example/project/social/SocialRequest.java
- src/main/java/com/example/project/social/SocialRestController.java
- src/main/java/com/example/project/social/SocialService.java
> 소셜 수정(카테고리 포함)

- src/main/resources/static/css/notjoined.css
- src/main/resources/static/css/style.css
- src/main/resources/templates/layout/header.mustache
- src/main/resources/templates/social/notJoinedForm.mustache
> 가입안한 소셜 페이지

- src/main/java/com/example/project/social_member/SocialMemberRequest.java
- src/main/java/com/example/project/social_member/SocialMemberRestController.java
- src/main/java/com/example/project/social_member/SocialMemberService.java
> 소셜 가입 승인, 거절 (소셜 마스터만 가능)

- src/main/java/com/example/project/user/UserRepository.java
- src/main/java/com/example/project/user/UserResponse.java
- src/main/java/com/example/project/user/UserRestController.java
- src/main/java/com/example/project/user/UserService.java
> 관리자 / 회원 상세 조회

- src/main/resources/static/css/bmodal.css
- src/main/resources/static/css/detail.css
- src/main/resources/static/css/style.css
- src/main/resources/templates/layout/header.mustache
- src/main/resources/templates/modal/boardModalForm.mustache
- src/main/resources/templates/social/detail.mustache
> 글보기, 글 모달 페이지

- src/main/java/com/example/project/_core/enums/CategoryNameStateEnum.java
- src/main/java/com/example/project/category_name/CategoryName.java
- src/main/java/com/example/project/category_name/CategoryNameRepository.java
- src/main/java/com/example/project/category_name/CategoryNameRequest.java
- src/main/java/com/example/project/category_name/CategoryNameResponse.java
- src/main/java/com/example/project/category_name/CategoryNameService.java
- src/main/java/com/example/project/social/SocialService.java
- src/main/java/com/example/project/user/AdminRestController.java
- src/main/resources/db/data.sql
> 관리자 / 카테고리 CRUD

- src/main/java/com/example/project/social/SocialResponse.java
- src/main/java/com/example/project/social/SocialService.java
- src/main/java/com/example/project/user/AdminRestController.java
> 관리자 / 소셜 상세 조회

- src/main/resources/static/css/common.css
- src/main/resources/templates/layout/post.mustache
> 게시글 해시태그 추가

- src/main/resources/static/css/bmodal.css
- src/main/resources/static/css/style.css
- src/main/resources/templates/layout/header.mustache
- src/main/resources/templates/modal/boardModalForm.mustache
> 알림 숫자 조정, 댓글 삭제버튼 추가

- src/main/java/com/example/project/social_member/SocialMemberRepository.java
- src/main/java/com/example/project/social_member/SocialMemberResponse.java
- src/main/java/com/example/project/social_member/SocialMemberService.java
- src/main/java/com/example/project/user/AdminRestController.java
- src/test/java/com/example/project/social_member/SocialMemberRepositoryTest.java
> 관리자 / 소셜 멤버 리스트 조회

- src/main/java/com/example/project/user/AdminRestController.java
> 관리자 / 소셜 삭제

- src/main/java/com/example/project/_core/enums/UserProviderEnum.java
- src/main/java/com/example/project/social/SocialResponse.java
- src/main/java/com/example/project/social/SocialService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/java/com/example/project/user/AdminRestController.java
- src/main/java/com/example/project/user/UserResponse.java
- src/main/resources/static/css/admin/admin.css
- src/main/resources/templates/admin/board/boardListForm.mustache
- src/main/resources/templates/admin/main.mustache
- src/main/resources/templates/admin/social/socialCategoryDetailForm.mustache
- src/main/resources/templates/admin/social/socialCategoryListForm.mustache
- src/main/resources/templates/admin/social/socialDetailForm.mustache
- src/main/resources/templates/admin/social/socialListForm.mustache
- src/main/resources/templates/admin/user/userDetailForm.mustache
- src/main/resources/templates/admin/user/userListForm.mustache
관리자 / 회원, 카테고리, 소셜, 게시글 관리 페이지 연결
> 관리자 / 회원, 카테고리, 소셜, 게시글 관리 페이지 연결

- src/main/java/com/example/project/board/BoardRepository.java
- src/main/java/com/example/project/board/BoardResponse.java
- src/main/java/com/example/project/board/BoardService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/resources/templates/admin/board/boardDetailForm.mustache
- src/main/resources/templates/admin/board/boardListForm.mustache
> 관리자 / 게시글 리스트, 상세 조회

- src/main/java/com/example/project/social/SocialController.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/resources/templates/admin/board/boardListForm.mustache
- src/main/resources/templates/admin/layout/sidebar.mustache
- src/main/resources/templates/admin/management/noticeDetailForm.mustache
- src/main/resources/templates/admin/management/noticeListForm.mustache
- src/main/resources/templates/admin/management/noticeUpdateForm.mustache
- src/main/resources/templates/admin/management/noticeWriteForm.mustache
- src/main/resources/templates/admin/management/qnaDetailForm.mustache
- src/main/resources/templates/admin/management/qnaListForm.mustache
- src/main/resources/templates/admin/management/reportDetailForm.mustache
- src/main/resources/templates/admin/management/reportListForm.mustache
- src/main/resources/templates/admin/social/socialCategoryListForm.mustache
- src/main/resources/templates/admin/social/socialListForm.mustache
- src/main/resources/templates/admin/user/userListForm.mustache
> 관리자 / 문의, 신고, 공지 페이지 연결

- src/main/java/com/example/project/qna/Qna.java
- src/main/java/com/example/project/qna/QnaRepository.java
- src/main/java/com/example/project/qna/QnaRequest.java
- src/main/java/com/example/project/qna/QnaResponse.java
- src/main/java/com/example/project/qna/QnaService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/resources/templates/admin/management/qnaDetailForm.mustache
- src/main/resources/templates/admin/management/qnaListForm.mustache
> 관리자 / 문의사항

- src/main/java/com/example/project/_core/enums/ReportResultEnum.java
- src/main/java/com/example/project/report/Report.java
- src/main/java/com/example/project/report/ReportRepository.java
- src/main/java/com/example/project/report/ReportResponse.java
- src/main/java/com/example/project/report/ReportService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/resources/db/data.sql
- src/main/resources/templates/admin/management/reportListForm.mustache
> 관리자 / 문의 신고 리스트

- src/main/java/com/example/project/notice/Notice.java
- src/main/java/com/example/project/notice/NoticeRepository.java
- src/main/java/com/example/project/notice/NoticeResponse.java
- src/main/java/com/example/project/notice/NoticeService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/resources/db/data.sql
- src/main/resources/templates/admin/management/noticeDetailForm.mustache
- src/main/resources/templates/admin/management/noticeListForm.mustache
> 관리자 / 공지 리스트, 상세 조회

- src/main/java/com/example/project/_core/enums/UserProviderEnum.java
- src/main/java/com/example/project/social/SocialResponse.java
- src/main/java/com/example/project/social/SocialService.java
- src/main/java/com/example/project/social_member/SocialMemberRepository.java
- src/main/java/com/example/project/social_member/SocialMemberResponse.java
- src/main/java/com/example/project/social_member/SocialMemberService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/java/com/example/project/user/AdminRestController.java
- src/main/java/com/example/project/user/UserResponse.java
- src/main/resources/templates/admin/social/socialDetailForm.mustache
- src/test/java/com/example/project/social_member/SocialMemberRepositoryTest.java
> [fix] 관리자 / 소셜 상세보기 및 멤버 목록보기

- src/main/java/com/example/project/user/AdminController.java
- src/main/java/com/example/project/user/UserController.java
- src/main/java/com/example/project/user/UserRepository.java
- src/main/java/com/example/project/user/UserService.java
- src/main/resources/static/css/admin/admin.css
- src/main/resources/templates/admin/layout/sidebar.mustache
- src/main/resources/templates/admin/user/userDetailForm.mustache
> 관리자 / 회원 강제 삭제

- src/main/java/com/example/project/social/SocialRepository.java
- src/main/java/com/example/project/social/SocialService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/resources/templates/admin/social/socialDetailForm.mustache
> 관리자 / 소셜 강제 삭제

- src/main/resources/static/css/style.css
- src/main/resources/templates/layout/post.mustache
> 답글보기 댓글 보기 추가

- src/main/java/com/example/project/category_name/CategoryNameRequest.java
- src/main/java/com/example/project/category_name/CategoryNameService.java
- src/main/java/com/example/project/user/AdminController.java
- src/main/resources/templates/admin/social/socialCategoryDetailForm.mustache
- src/main/resources/templates/admin/social/socialCategoryListForm.mustache
- src/main/resources/templates/admin/social/socialCategoryRegisterForm.mustache
- src/main/resources/templates/admin/social/socialCategoryUpdateForm.mustache
> 관리자 / 카테고리 등록, 수정, 삭제

- src/main/java/com/example/project/_core/enums/ReportResultEnum.java
- src/main/java/com/example/project/board/BoardRepository.java
- src/main/java/com/example/project/category_name/CategoryNameRepository.java
- src/main/java/com/example/project/qna/QnaRepository.java
- src/main/java/com/example/project/report/ReportResponse.java
- src/main/java/com/example/project/social/SocialRepository.java
- src/main/java/com/example/project/user/UserRepository.java
관리자 / 정렬 수정 및 reportResultEnum 변경
> 관리자 / 정렬 수정 및 reportResultEnum 변경
